### ISSUE TITLE
Automatická aktualizace šablony

### ISSUE THREAD

**Issue by kalich5** [skaut/dsw-skaut-svs#1]
Umožnit automatickou aktualizaci z GitHubu. Něco v tomto smyslu...
skaut/dsw-oddil#122

**Comment by kalich5** [comment]
@vojta001 mohl by jsi přidat tu možnost aktualizace přímo z GitHubu. Děkuju

**Comment by kalich5** [comment]
@vojta001 jak to vidíš? 👍

**Comment by vojta001** [comment]
Věřím, že by to takto mělo fungovat, ale potřebuje to otestovat. Buďto nějaký beta release, nebo dočasný, který se pak smaže.

**Comment by kalich5** [comment]
máš tam betu, klidně pak vytvoř další (0.2-beta) a zkus to.

**Comment by vojta001** [comment]
Díky, zítra se na to vrhnu

**Comment by kalich5** [comment]
Verzi 0.1 jsem teď vytvořil a na jeden web nainstaloval. Připravil jsem všechno na verzi 0.2 a tu vydám zítra dopoledne. A uvidíme, jestli se to povede. :-)

**Comment by kalich5** [comment]
Tak jsem vydal i 0.2 a na webu se vůbec nic neděje. Pořád mám 0.1 verzi.

**Comment by vojta001** [comment]
Už to vidím, aktualizační funkce předpokládá (po vzoru dsw-oddil), že k release bude příloha se jménem splňujícím regexp `dsw-skaut-svs-\d+\.\d+\.\d+-compiled\.zip`.
Buďto to budeme takto držet, nebo, pokud nebude šablonu třeba "kompilovat", může si to klidně stáhnout zdroják aktuální při vydání toho release.

**Comment by kalich5** [comment]
To bych určitě vydával, jako u DSW. Jak by se tedy měl jmenovat ten soubor? Teď je to 0.1.....

**Comment by vojta001** [comment]
Tady jde o to, že dsw-oddil se "kompiluje", mezi zdrojákem a produktem probíhá překlad, který zajišťuje Grunt. Pokud vím, dsw-skaut-svs nic takového nepotřebuje, takže jediný důvod, proč nepoužít zdroják je možnost to trochu pročistit (např. `.gitignore`).
Pokud jde o jméno, musí splňovat regexp `dsw-skaut-svs-\d+\.\d+\.\d+-compiled\.zip`, tedy např. `dsw-skaut-svs-0.0.1-compiled.zip`.

**Comment by kalich5** [comment]
Tak ten kód nějak zjednoduš. Teď jsou verze dsw-skaut-svs-0.1.zip a to úplně podle mě stačí. Děkuju

**Comment by vojta001** [comment]
Mimochodem na jakou minimální verzi PHP cílíme? Jde mi především o srandy jako [type hinting](https://secure.php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration) apod.

**Comment by vojta001** [comment]
Tak jo, nová **neotestovaná** verze je tady. Když nad tím tak přemýšlím, myslím si, že je lepší než ta na dsw-oddil. Osvědčí-li se to takto, navrhuju to předělat i tam. Každopádně releases se nově musí jmenovat `v<číslo>.<číslo>`, např. `v1.0`. Naproti tomu jejich příloha už verzi neobsahuje, takže tam zákonitě může být jen jedna. Její jméno je `dsw-skaut-svs-release.zip`.

**Comment by vojta001** [comment]
Připravil jsem testovací releases, ty staré bohužel nemám právo smazat.

**Comment by kalich5** [comment]
PHP 7.x a novější. Jako další věci co teď děláme

**Comment by kalich5** [comment]
Staré jsem smazal

**Comment by kalich5** [comment]
Tak to zkouším, a nějak to nefunguje. Mám na webu verzi 0.1 a na verzi 0.2 se tomu nějak nechce

**Comment by kalich5** [comment]
Beru zpět, chvíli to trvalo ale teď se mi aktualizace nabídnula.

**Comment by kalich5** [comment]
@vojta001 můžeš kouknout na tu verzi 1.0 prosím? Nějak se tomu z verze 0.2 nechce aktualizovat. Přijde mi, že jsem to udělal úplně stejně jako ty dvě minulé.
